### PR TITLE
work around RAs RUSTC_WRAPPER hack

### PR DESCRIPTION
**Pull request by RalfJung**
Works around https://github.com/rust-lang/rust-analyzer/issues/12973 by un-doing parts of what https://github.com/dtolnay/anyhow/pull/157 intended to do, but only https://github.com/dtolnay/anyhow/pull/249 actually did: honoring RUSTC_WRAPPER.

@jonhoo are you aware of any cases where ignoring RUSTC_WRAPPER actually causes problems? Seeing as autocfg ignores RUSTC_WRAPPER, it seems unlikely to me.

### CODE REVIEW

**Comment by RalfJung** [comment]
Note that this matches the behavior before https://github.com/dtolnay/anyhow/pull/249, because anyhow used to check the wrong env var for this.

**Comment by jonhoo** [comment]
I don't actually know of a use of `RUSTC_WRAPPER`, so can't really add much info. I've heard of it being used to always append certain `rustc` flags no matter which source is used for the rustc flags that Cargo decides to use, but don't have a concrete example I can link to.

**Review by dtolnay — CHANGES_REQUESTED** [review]
I would prefer to ignore only rust-analyzer's buggy RUSTC_WRAPPER specifically. Does it have some kind of recognizable name we could look for?

**Comment by RalfJung** [comment]
> I would prefer to ignore only rust-analyzer's buggy RUSTC_WRAPPER specifically. Does it have some kind of recognizable name we could look for?

I'll have to forward that question to @lnicola

**Comment by lnicola** [comment]
> Does it have some kind of recognizable name we could look for?

RA sets itself as the wrapper, so it should be called `rust-analyzer` or `rust-analyzer.exe`. However,

 - a tool based on RA might use the same approach
 - as mentioned in the issue, IntelliJ Rust [takes the same approach](https://github.com/intellij-rust/intellij-rust/tree/3ec36ffd96c31b6e1252e473fe8f133fbf1e2d33/native-helper) (which is where we stole it from from)

**Comment by RalfJung** [comment]
This should help for RA, not sure if we want to start carrying a list of all the broken wrappers out there...

**Comment by jonhoo** [comment]
I've found one use of `RUSTC_WRAPPER` in an internal code-base, and it's used to append to `$PATH` before delegating to the real `rustc`. And I'm not even sure that particular use is needed any more. That said, it does feel unfortunate to ignore `RUSTC_WRAPPER` entirely — even though _I_ don't need it, chances are that if someone _does_ set it it makes a difference to their use-case.

**Comment by RalfJung** [comment]
OTOH, given that autocfg is widely used and https://github.com/cuviper/autocfg/issues/26 has seen very little activity, it doesn't seem to be terribly common for RUSTC_WRAPPER to be used in a way that just ignoring it causes a lot of trouble.

**Review by dtolnay — COMMENTED** [review]
I put up a different workaround in #252 since I think I would prefer not to sweep this under the rug yet as done by this PR.

I would be open to the workaround from this PR only if https://github.com/rust-lang/rust-analyzer/issues/12973 is accepted as a rust-analyzer defect and we see progress toward resolving it, or if someone makes a compelling case that https://github.com/rust-lang/rust-analyzer/issues/12973 is not a rust-analyzer defect and rust-analyzer will therefore not change behavior. The thing I don't want is for this workaround to land and then no follow-up ever occurs about the root cause.

**Comment by RalfJung** [comment]
Sure, that also works. I locally disabled the rustc-wrapper hack anyway, just posted this because I felt bad for my previous PR triggering that problem.

**Pull request closed without merging**
